### PR TITLE
Fix memory load with limited bit width

### PR DESCRIPTION
**Pull request by MaxDesiatov**
This change fixes `load` instructions not respecting bit width parts. For example, `i32.load8_u` was loading all i32 bytes instead of a single byte.

Also, the page size was specified as 6K, while it's 64K according to the spec.

This increases the amount of spec tests passing from 25% in `master` to 33% in this branch.

### CODE REVIEW

**Comment by akkyie** [comment]
Hi @MaxDesiatov, I’m happy to see you’re working on it!

It’s been a while since the last time I touched this repo and stopped keeping up with the WASM spec, and now I think it’s hard to make time to give my knowledge a brush-up enough to commit or review.
So, can I offer you the complete maintainer-ship of this project? Let me know if transferring the repository is desirable.

(Changes looks good to me btw :)

**Comment by MaxDesiatov** [comment]
Many thanks for your previous work on this. It seems you've covered all of the foundational parts of the spec. I anticipate it's going to be relatively easy to get to 100% of the spec covered.

I really appreciate the offer! I hope to get to 100% spectests passing at some point and to potentially use WAKit as a Wasm debugger. Being written in Swift would allow to be easily embedded in GUI apps. My dream is to have a visual debugger that displays the current state of the VM with its memory and instructions executed.

Would you be open transferring the repo to the SwiftWasm org then?

I will also update `README.md` accordingly to credit your work and mention you as the original maintainer.

**Comment by MaxDesiatov** [comment]
You can transfer to my account for now, but let me know if you'd like to join SwiftWasm in any capacity. Would be very happy to see you there as a member and a contributor!

**Comment by MaxDesiatov** [comment]
Just noticed I had a fork of this repo with the same name on my account. I've deleted it. If that prevent transfers to my account previously, please try again.

**Comment by akkyie** [comment]
@MaxDesiatov Sorry for the delay (and messing up your PR...,) I requested transfer of this repository!

**Comment by MaxDesiatov** [comment]
I don't think anything is messed up, all looks great. Thank you so much!

**Pull request merged**
